// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3vqenMazqEjp65gtz18X2CxlO-ppF26I',
    appId: '1:545709391248:web:9a6fdaf19e233a59c98715',
    messagingSenderId: '545709391248',
    projectId: 'intruder-eaa8f',
    authDomain: 'intruder-eaa8f.firebaseapp.com',
    storageBucket: 'intruder-eaa8f.firebasestorage.app',
    measurementId: 'G-B9YFKLP4XV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL86j-dRYpTpUZ53dLN4otxJvctHwYrXg',
    appId: '1:545709391248:android:68289e298e806405c98715',
    messagingSenderId: '545709391248',
    projectId: 'intruder-eaa8f',
    storageBucket: 'intruder-eaa8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApiZYwDLdlFfxqp9NdpMiLH-uSxQrl1ts',
    appId: '1:545709391248:ios:f8e698f7004302dfc98715',
    messagingSenderId: '545709391248',
    projectId: 'intruder-eaa8f',
    storageBucket: 'intruder-eaa8f.firebasestorage.app',
    iosBundleId: 'com.example.intruder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApiZYwDLdlFfxqp9NdpMiLH-uSxQrl1ts',
    appId: '1:545709391248:ios:f8e698f7004302dfc98715',
    messagingSenderId: '545709391248',
    projectId: 'intruder-eaa8f',
    storageBucket: 'intruder-eaa8f.firebasestorage.app',
    iosBundleId: 'com.example.intruder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3vqenMazqEjp65gtz18X2CxlO-ppF26I',
    appId: '1:545709391248:web:16a4b10d570f53f9c98715',
    messagingSenderId: '545709391248',
    projectId: 'intruder-eaa8f',
    authDomain: 'intruder-eaa8f.firebaseapp.com',
    storageBucket: 'intruder-eaa8f.firebasestorage.app',
    measurementId: 'G-ZT9NMNXX1L',
  );
}
